Frontend - podstawowe funkcjonalności
mpfmorawski/git-to-know-me pull request #30
Opened 2022-05-17 21:59 UTC by kamilwil

Pierwsza wersja rozwinięcia interfejsu graficznego o:

- globalne statystyki użytkownika
- wykres języków programowania
- panel z listą repozytoriów

Stan na 17.05.2022 23:58: aktualnie tylko statyczny content, ale przygotowany do integracji z agregacją danych od @jprokopczuk

2022-05-25 13:10 UTC, mpfmorawski commented
@kamilwil, proszę o krótki raport (najlepiej listę) z informacją, co zostało do zaimplementowania, żeby móc zmienić status z Draft na Ready for review

2022-05-27 03:44 UTC, kamilwil commented
Kwestie funkcjonalne:
- [ ] wyświetlanie rzeczywistych danych w kafelku z wykresem języków
- [ ] logika kafelka z listą repo (oczekuje na poprawkę od @jprokopczuk

Kwestie wizualne:
- [ ] zwiększenie marginesów strony
- [ ] reorganizacja kafelków
- [ ] poprawka glitchy przy przełączaniu widoku do jednej kolumny
- [ ] poprawka formatowania listy języków przy wykresie

2022-06-02 09:31 UTC, pktiuk requested changes
![image](https://user-images.githubusercontent.com/45544416/171600606-74c60aa4-0a55-4d60-9a40-83152ac4e94d.png)


To nie powinno tak wyglądać

Tak poza tym to powinno być chyba 5 repozytoriów u mnie, ale to chyba nie kwestia frontu. (no i gwiazdki się nie zgadzają)

EDIT  
Właśnie zauważyłem, że da się to przewijać. Wydaje mi się jednak, że albo ten kafelek powinien być wyższy, aby pokazywać wszsystko, albo powinien być widoczny jakiś suwak sugerujący, że można przewinąć

2022-06-02 09:33 UTC, pktiuk commented on .github/workflows/autoyapf.yml
>          if: steps.git-check.outputs.modified == 'true'
Czy ta zmiana nie została już raz dodana w: https://github.com/mpfmorawski/git-to-know-me/pull/28/files
https://github.com/mpfmorawski/git-to-know-me/pull/28/files ?

Ustalcie z @KarolNiem który z was chce to dodać, bo inaczej będzie konflikt

2022-06-02 16:46 UTC, pktiuk commented
![image](https://user-images.githubusercontent.com/45544416/171681916-1646429b-fb46-4d53-b1ec-a5c9fb77177c.png)
Już nic nie wystaje ;)  
(firefox)

2022-06-05 14:19 UTC, mpfmorawski approved these changes
Po zmianach wprowadzonych od wczoraj przez @kamilwil wszystko u mnie wygląda już elegancko. Zatwierdzam.

![image](https://user-images.githubusercontent.com/62252131/172055034-c7b89a82-2c3b-4cd6-8784-16f48d0cc98b.png)
![image](https://user-images.githubusercontent.com/62252131/172055050-162e1540-a0ca-4d4e-ab9a-278e0277a588.png)

2022-06-05 14:50 UTC, KarolNiem approved these changes

2022-06-06 15:42 UTC, merged